### PR TITLE
Changed to accessing network by ref, added lint step

### PR DESCRIPTION
**Pull request by Wokstym**

### CODE REVIEW

**Comment by ZachHaber** [comment]
Try adding prettier as a dev dependency. I think it's just using a really old version or something by default.

**Review by ZachHaber — APPROVED** [review]
Looks good to me :)

**Comment by ZachHaber** [comment]
A thought, would it make more sense to instead of using forwardRef and `ref` use a prop called `networkRef`?

**Comment by Wokstym** [comment]
For me how it is right now is fine enough, maybe we will revisit it in the future

**Pull request merged**
