### PR TITLE
storybook added

### PR DESCRIPTION
**Pull request by WikKam**
I've added storybook to the project with an example of basic graph. Run `yarn storybook` to see this.

### CODE REVIEW

**Comment by WikKam** [comment]
It looks like this: 
image

**Comment by ZachHaber** [comment]
Works great for me!
I feel like we should get rid of the "Example" folder and use the storybook site generation as the github page from now on, as we're more  likely to add examples to the storybook than the example.

Edit:

It appears there's some wonkiness we should look into when you change the variables from the storybook actions, I somewhat randomly am getting "duplicate id" errors, I was also able to manipulate it to indicate a circular edge that shouldn't be one.
Though when I have time, I can work on debugging that after we merge this in.
image

**Comment by WikKam** [comment]
> It appears there's some wonkiness we should look into when you change the variables from the storybook actions, I somewhat randomly am getting "duplicate id" errors, I was also able to manipulate it to indicate a circular edge that shouldn't be one.
> Though when I have time, I can work on debugging that after we merge this in.

Let's create separate issue for that. I've removed the "example" folder.

**Review by ZachHaber — APPROVED** [review]

**Review by Wokstym — APPROVED** [review]
Looks great

**Pull request merged**
